<a href="https://colab.research.google.com/github/farihahahmed/solar-forecasting-AI-novel-cyclical-features-encoding-technique/blob/main/5_Cyclical_Features_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Loading the data

In [ ]:
#Mounting Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#Importing Our Data
import pandas as pd

x = pd.read_csv('/content/drive/MyDrive/Restarting Lumiere - Farihah and Mauricio/Notebooks and data/xwtime.csv')
y = pd.read_csv('/content/drive/MyDrive/Restarting Lumiere - Farihah and Mauricio/Notebooks and data/ywtime.csv')

In [ ]:
x

        Unnamed: 0  customer_num     date  ...  23:00-day2  23:30-day2  0:00-day2
0                0             1   1/7/12  ...         0.0         0.0        0.0
1                1             1   2/7/12  ...         0.0         0.0        0.0
2                2             1   3/7/12  ...         0.0         0.0        0.0
3                3             1   4/7/12  ...         0.0         0.0        0.0
4                4             1   5/7/12  ...         0.0         0.0        0.0
...            ...           ...      ...  ...         ...         ...        ...
108814      108814           300  24/6/13  ...         0.0         0.0        0.0
108815      108815           300  25/6/13  ...         0.0         0.0        0.0
108816      108816           300  26/6/13  ...         0.0         0.0        0.0
108817      108817           300  27/6/13  ...         0.0         0.0        0.0
108818      108818           300  28/6/13  ...         0.0         0.0        0.0

[108819 rows x 99 columns]

In [ ]:
y

        Unnamed: 0  customer_num     date  ...  23:00-day1  23:30-day1  0:00-day1
0                0             1   3/7/12  ...         0.0         0.0        0.0
1                1             1   4/7/12  ...         0.0         0.0        0.0
2                2             1   5/7/12  ...         0.0         0.0        0.0
3                3             1   6/7/12  ...         0.0         0.0        0.0
4                4             1   7/7/12  ...         0.0         0.0        0.0
...            ...           ...      ...  ...         ...         ...        ...
108814      108814           300  26/6/13  ...         0.0         0.0        0.0
108815      108815           300  27/6/13  ...         0.0         0.0        0.0
108816      108816           300  28/6/13  ...         0.0         0.0        0.0
108817      108817           300  29/6/13  ...         0.0         0.0        0.0
108818      108818           300  30/6/13  ...         0.0         0.0        0.0

[108819 rows x 51 columns]

In [ ]:
x = x.drop(["Unnamed: 0"], axis=1)
y = y.drop(["Unnamed: 0"], axis=1)

In [ ]:
print(x.shape)
print(y.shape)

(108819, 98)
(108819, 50)

#Cyclical features encoding

In [ ]:
x

        customer_num     date  0:30-day1  ...  23:00-day2  23:30-day2  0:00-day2
0                  1   1/7/12        0.0  ...         0.0         0.0        0.0
1                  1   2/7/12        0.0  ...         0.0         0.0        0.0
2                  1   3/7/12        0.0  ...         0.0         0.0        0.0
3                  1   4/7/12        0.0  ...         0.0         0.0        0.0
4                  1   5/7/12        0.0  ...         0.0         0.0        0.0
...              ...      ...        ...  ...         ...         ...        ...
108814           300  24/6/13        0.0  ...         0.0         0.0        0.0
108815           300  25/6/13        0.0  ...         0.0         0.0        0.0
108816           300  26/6/13        0.0  ...         0.0         0.0        0.0
108817           300  27/6/13        0.0  ...         0.0         0.0        0.0
108818           300  28/6/13        0.0  ...         0.0         0.0        0.0

[108819 rows x 98 columns]

In [ ]:
from datetime import datetime

x['date'] = pd.to_datetime(x['date'], format='%d/%m/%y')

In [ ]:
x['month'] = x['date'].dt.month

In [ ]:
x['day'] = x['date'].dt.day

In [ ]:
x = x.drop(["date", "customer_num"], axis=1)

In [ ]:
y['date'] = pd.to_datetime(y['date'], format='%d/%m/%y')

In [ ]:
y['month'] = y['date'].dt.month

In [ ]:
y['day'] = y['date'].dt.day

In [ ]:
y = y.drop(["date", "customer_num"], axis=1)

#Converting to pi scale, then sin and cos

In [ ]:
import math
import numpy as np
x["month_norm"] = 2 * math.pi * x["month"] / x["month"].max()
x["month_cos"] = np.cos(x["month_norm"])
x["month_sin"] = np.sin(x["month_norm"])

In [ ]:
x["day_norm"] = 2 * math.pi * x["day"] / x["day"].max()
x["day_cos"] = np.cos(x["day_norm"])
x["day_sin"] = np.sin(x["day_norm"])

In [ ]:
x = x.drop(["month", "day"], axis=1)

In [ ]:
x = x.drop(["month_norm", "day_norm"], axis = 1)

In [ ]:
y["month_norm"] = 2 * math.pi * y["month"] / y["month"].max()
y["month_cos"] = np.cos(y["month_norm"])
y["month_sin"] = np.sin(y["month_norm"])

In [ ]:
y["day_norm"] = 2 * math.pi * y["day"] / y["day"].max()
y["day_cos"] = np.cos(y["day_norm"])
y["day_sin"] = np.sin(y["day_norm"])

In [ ]:
y = y.drop(["month", "day"], axis=1)

In [ ]:
y = y.drop(["month_norm", "day_norm"], axis = 1)

In [ ]:
y

        0:30-day1  1:00-day1  1:30-day1  ...     month_sin   day_cos   day_sin
0             0.0        0.0        0.0  ... -5.000000e-01  0.820763  0.571268
1             0.0        0.0        0.0  ... -5.000000e-01  0.688967  0.724793
2             0.0        0.0        0.0  ... -5.000000e-01  0.528964  0.848644
3             0.0        0.0        0.0  ... -5.000000e-01  0.347305  0.937752
4             0.0        0.0        0.0  ... -5.000000e-01  0.151428  0.988468
...           ...        ...        ...  ...           ...       ...       ...
108814        0.0        0.0        0.0  ...  1.224647e-16  0.528964 -0.848644
108815        0.0        0.0        0.0  ...  1.224647e-16  0.688967 -0.724793
108816        0.0        0.0        0.0  ...  1.224647e-16  0.820763 -0.571268
108817        0.0        0.0        0.0  ...  1.224647e-16  0.918958 -0.394356
108818        0.0        0.0        0.0  ...  1.224647e-16  0.979530 -0.201299

[108819 rows x 52 columns]

#Train Test Split

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1, random_state = 1, shuffle = False)

#Normalization

In [ ]:
# data normalization with sklearn
from sklearn.preprocessing import MinMaxScaler

# fit scaler on training data
norm = MinMaxScaler().fit(x_train)

# transform training data
x_train_norm = norm.transform(x_train)

# transform testing dataabs
x_test_norm = norm.transform(x_test)

# Linear Regression Model

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
import numpy as np

#model
lr = LinearRegression()

# fit
lr.fit(x_train_norm, y_train)

# predict
pred = lr.predict(x_test_norm)

# RMSE
print("RMSE: " + str(np.sqrt(mean_squared_error(y_test,pred))))

#MAE
print("MAE: " + str(mean_absolute_error(y_test, pred)))

RMSE: 0.09422510100115998
MAE: 0.035768349575505946

In [ ]:
#Finding pearson's correlation coefficient between
#real value and predicted value

y_test = np.array(y_test, dtype ='float32')
pred = np.array(pred, dtype ='float32')
new_y = y_test.reshape(565864, 1)
new_y = np.squeeze(new_y)
new_p = pred.reshape(565864, 1)
new_p = np.squeeze(new_p)

from scipy.stats import pearsonr
corr, _ = pearsonr(new_p, new_y)
print('Pearsons correlation: %.4f' % corr)

Pearsons correlation: 0.9552

#KNN Model

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error

#model
knn = KNeighborsRegressor(n_neighbors=7)

# fit
knn.fit(x_train_norm,y_train)

# predict
pred = knn.predict(x_test_norm)

# RMSE
print("RMSE: " + str(np.sqrt(mean_squared_error(y_test,pred))))

#MAE
print("MAE: " + str(mean_absolute_error(y_test, pred)))

RMSE: 0.0802754190274742
MAE: 0.026921215324594374

In [ ]:
#Finding pearson's correlation coefficient between
#real value and predicted value

y_test = np.array(y_test, dtype ='float32')
pred = np.array(pred, dtype ='float32')
new_y = y_test.reshape(565864, 1)
new_y = np.squeeze(new_y)
new_p = pred.reshape(565864, 1)
new_p = np.squeeze(new_p)

from scipy.stats import pearsonr
corr, _ = pearsonr(new_p, new_y)
print('Pearsons correlation: %.4f' % corr)

Pearsons correlation: 0.9685

#Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error

# model
dt = DecisionTreeRegressor(max_depth=10,random_state=27)

# fit
dt.fit(x_train_norm, y_train)

# predict
pred = dt.predict(x_test_norm)

# RMSE
print("RMSE: " + str(np.sqrt(mean_squared_error(y_test,pred))))

#MAE
print("MAE: " + str(mean_absolute_error(y_test, pred)))

RMSE: 0.11373276407104858
MAE: 0.045998244549671614

In [ ]:
#Finding pearson's correlation coefficient between
#real value and predicted value

y_test = np.array(y_test, dtype ='float32')
pred = np.array(pred, dtype ='float32')
new_y = y_test.reshape(565864, 1)
new_y = np.squeeze(new_y)
new_p = pred.reshape(565864, 1)
new_p = np.squeeze(new_p)

from scipy.stats import pearsonr
corr, _ = pearsonr(new_p, new_y)
print('Pearsons correlation: %.4f' % corr)

Pearsons correlation: 0.9345

#MLP Regressor

In [ ]:
from sklearn.neural_network import MLPRegressor

#model
mlp = MLPRegressor(random_state=1, max_iter=30)

# fit
mlp.fit(x_train_norm,y_train)

# predict
pred = mlp.predict(x_test_norm)

# RMSE
print("RMSE: " + str(np.sqrt(mean_squared_error(y_test,pred))))

#MAE
print("MAE: " + str(mean_absolute_error(y_test, pred)))

RMSE: 0.09027122998787525
MAE: 0.036827093064449465

In [ ]:
#Finding pearson's correlation coefficient between
#real value and predicted value

y_test = np.array(y_test, dtype ='float32')
pred = np.array(pred, dtype ='float32')
new_y = y_test.reshape(565864, 1)
new_y = np.squeeze(new_y)
new_p = pred.reshape(565864, 1)
new_p = np.squeeze(new_p)

from scipy.stats import pearsonr
corr, _ = pearsonr(new_p, new_y)
print('Pearsons correlation: %.4f' % corr)

Pearsons correlation: 0.9590

#Random Forest

In [ ]:
from sklearn.ensemble import RandomForestRegressor

#model
rf = RandomForestRegressor(n_estimators=20, random_state=1)

# fit
rf.fit(x_train_norm,y_train)

# predict
pred = rf.predict(x_test_norm)

# RMSE
print("RMSE: " + str(np.sqrt(mean_squared_error(y_test,pred))))

#MAE
print("MAE: " + str(mean_absolute_error(y_test, pred)))

RMSE: 0.07809918621389944
MAE: 0.026678358733113937

In [ ]:
#Finding pearson's correlation coefficient between
#real value and predicted value

y_test = np.array(y_test, dtype ='float32')
pred = np.array(pred, dtype ='float32')
new_y = y_test.reshape(565864, 1)
new_y = np.squeeze(new_y)
new_p = pred.reshape(565864, 1)
new_p = np.squeeze(new_p)

from scipy.stats import pearsonr
corr, _ = pearsonr(new_p, new_y)
print('Pearsons correlation: %.4f' % corr)

Pearsons correlation: 0.9695

#NN #1

- 3 dense layers
- 96 to 500 to 8 to 48
- 10 epochs

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from keras import Input

In [ ]:
# define the keras model
model1 = Sequential()
model1.add(Dense(500, input_dim=100, activation='relu'))
model1.add(Dense(8, activation='relu'))
model1.add(Dense(52))
model1.compile(loss='mse', optimizer='adam')
# fit the keras model on the dataset
model1.fit(x_train_norm, y_train, epochs=10)

Epoch 1/10
3061/3061 [==============================] - 14s 4ms/step - loss: 0.0200
Epoch 2/10
3061/3061 [==============================] - 12s 4ms/step - loss: 0.0117
Epoch 3/10
3061/3061 [==============================] - 15s 5ms/step - loss: 0.0114
Epoch 4/10
3061/3061 [==============================] - 13s 4ms/step - loss: 0.0111
Epoch 5/10
3061/3061 [==============================] - 13s 4ms/step - loss: 0.0109
Epoch 6/10
3061/3061 [==============================] - 12s 4ms/step - loss: 0.0106
Epoch 7/10
3061/3061 [==============================] - 12s 4ms/step - loss: 0.0105
Epoch 8/10
3061/3061 [==============================] - 12s 4ms/step - loss: 0.0102
Epoch 9/10
3061/3061 [==============================] - 7s 2ms/step - loss: 0.0100
Epoch 10/10
3061/3061 [==============================] - 7s 2ms/step - loss: 0.0099

In [ ]:
#Saving our model
from keras.models import model_from_json
model1_json = model1.to_json()
with open("model1.json", "w") as json_file:
    json_file.write(model1_json)
model1.save_weights("model1.h5")
print("Saved model to disk")

Saved model to disk

In [ ]:
#Loading our model
json_file = open('model1.json', 'r')
loaded_model1_json = json_file.read()
json_file.close()
loaded_model1 = model_from_json(loaded_model1_json)
# load weights into new model
loaded_model1.load_weights("model1.h5")
print("Loaded model from disk")
loaded_model1.compile(loss='mse', optimizer='adam')

Loaded model from disk

In [ ]:
pred = loaded_model1.predict(x_test_norm)
print(np.sqrt(mean_squared_error(y_test,pred)))
print(mean_absolute_error(y_test, pred))

0.09471304
0.044989526

In [ ]:
#Finding pearson's correlation coefficient between
#real value and predicted value

y_test = np.array(y_test, dtype ='float32')
pred = np.array(pred, dtype ='float32')
new_y = y_test.reshape(565864, 1)
new_y = np.squeeze(new_y)
new_p = pred.reshape(565864, 1)
new_p = np.squeeze(new_p)

from scipy.stats import pearsonr
corr, _ = pearsonr(new_p, new_y)
print('Pearsons correlation: %.4f' % corr)

Pearsons correlation: 0.9550

#NN #2

- 3 dense layers
- 96 to 1000 to 8 to 48
- 10 epochs

In [ ]:
# define the keras model
model2 = Sequential()
model2.add(Dense(1000, input_dim=100, activation='relu'))
model2.add(Dense(8, activation='relu'))
model2.add(Dense(52))
model2.compile(loss='mse', optimizer='adam')
# fit the keras model on the dataset
model2.fit(x_train_norm, y_train, epochs=10)

Epoch 1/10
3061/3061 [==============================] - 11s 3ms/step - loss: 0.0319
Epoch 2/10
3061/3061 [==============================] - 11s 4ms/step - loss: 0.0211
Epoch 3/10
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0208
Epoch 4/10
3061/3061 [==============================] - 12s 4ms/step - loss: 0.0205
Epoch 5/10
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0202
Epoch 6/10
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0200
Epoch 7/10
3061/3061 [==============================] - 11s 3ms/step - loss: 0.0198
Epoch 8/10
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0196
Epoch 9/10
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0194
Epoch 10/10
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0193

In [ ]:
#Saving our model
from keras.models import model_from_json
model2_json = model2.to_json()
with open("model2.json", "w") as json_file:
    json_file.write(model2_json)
model2.save_weights("model2.h5")
print("Saved model to disk")

Saved model to disk

In [ ]:
#Loading our model
json_file = open('model2.json', 'r')
loaded_model2_json = json_file.read()
json_file.close()
loaded_model2 = model_from_json(loaded_model2_json)
# load weights into new model
loaded_model2.load_weights("model2.h5")
print("Loaded model from disk")
loaded_model2.compile(loss='mse', optimizer='adam')

Loaded model from disk

In [ ]:
pred = loaded_model2.predict(x_test_norm)
print(np.sqrt(mean_squared_error(y_test,pred)))
print(mean_absolute_error(y_test, pred))

0.13431282
0.0597896

In [ ]:
#Finding pearson's correlation coefficient between
#real value and predicted value

y_test = np.array(y_test, dtype ='float32')
pred = np.array(pred, dtype ='float32')
new_y = y_test.reshape(565864, 1)
new_y = np.squeeze(new_y)
new_p = pred.reshape(565864, 1)
new_p = np.squeeze(new_p)

from scipy.stats import pearsonr
corr, _ = pearsonr(new_p, new_y)
print('Pearsons correlation: %.4f' % corr)

Pearsons correlation: 0.9067

#NN #3

- 3 dense layers
- 96 to 1000 to 8 to 48
- 15 epochs

In [ ]:
# define the keras model
model3 = Sequential()
model3.add(Dense(1000, input_dim=100, activation='relu'))
model3.add(Dense(8, activation='relu'))
model3.add(Dense(52))
model3.compile(loss='mse', optimizer='adam')
# fit the keras model on the dataset
model3.fit(x_train_norm, y_train, epochs=15)

Epoch 1/15
3061/3061 [==============================] - 11s 3ms/step - loss: 0.0213
Epoch 2/15
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0117
Epoch 3/15
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0113
Epoch 4/15
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0111
Epoch 5/15
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0107
Epoch 6/15
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0105
Epoch 7/15
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0103
Epoch 8/15
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0102
Epoch 9/15
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0100
Epoch 10/15
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0099
Epoch 11/15
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0097
Epoch 12/15
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0097
Epoch 13/15
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0095
Epoch 14/15
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0095
Epoch 15/15
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0095

In [ ]:
#Saving our model
from keras.models import model_from_json
model3_json = model3.to_json()
with open("model3.json", "w") as json_file:
    json_file.write(model3_json)
model3.save_weights("model3.h5")
print("Saved model to disk")

Saved model to disk

In [ ]:
#Loading our model
json_file = open('model3.json', 'r')
loaded_model3_json = json_file.read()
json_file.close()
loaded_model3 = model_from_json(loaded_model3_json)
# load weights into new model
loaded_model3.load_weights("model3.h5")
print("Loaded model from disk")
loaded_model3.compile(loss='mse', optimizer='adam')

Loaded model from disk

In [ ]:
pred = loaded_model3.predict(x_test_norm)
print(np.sqrt(mean_squared_error(y_test,pred)))
print(mean_absolute_error(y_test, pred))

0.09334575
0.043483607

In [ ]:
#Finding pearson's correlation coefficient between
#real value and predicted value

y_test = np.array(y_test, dtype ='float32')
pred = np.array(pred, dtype ='float32')
new_y = y_test.reshape(565864, 1)
new_y = np.squeeze(new_y)
new_p = pred.reshape(565864, 1)
new_p = np.squeeze(new_p)

from scipy.stats import pearsonr
corr, _ = pearsonr(new_p, new_y)
print('Pearsons correlation: %.4f' % corr)

Pearsons correlation: 0.9571

#NN #4

- 2 dense layers
- 96 to 100 to 48
- 10 epochs

In [ ]:
model4 = Sequential()
model4.add(Dense(100, activation='relu', input_dim=100))
model4.add(Dense(52))
model4.compile(optimizer='adam', loss='mse')
model4.fit(x_train_norm, y_train, epochs=10)

Epoch 1/10
3061/3061 [==============================] - 7s 2ms/step - loss: 0.0113
Epoch 2/10
3061/3061 [==============================] - 6s 2ms/step - loss: 0.0089
Epoch 3/10
3061/3061 [==============================] - 6s 2ms/step - loss: 0.0087
Epoch 4/10
3061/3061 [==============================] - 6s 2ms/step - loss: 0.0085
Epoch 5/10
3061/3061 [==============================] - 6s 2ms/step - loss: 0.0083
Epoch 6/10
3061/3061 [==============================] - 6s 2ms/step - loss: 0.0082
Epoch 7/10
3061/3061 [==============================] - 6s 2ms/step - loss: 0.0081
Epoch 8/10
3061/3061 [==============================] - 6s 2ms/step - loss: 0.0080
Epoch 9/10
3061/3061 [==============================] - 6s 2ms/step - loss: 0.0079
Epoch 10/10
3061/3061 [==============================] - 6s 2ms/step - loss: 0.0078

In [ ]:
#Saving our model
from keras.models import model_from_json
model4_json = model4.to_json()
with open("model4.json", "w") as json_file:
    json_file.write(model4_json)
model4.save_weights("model4.h5")
print("Saved model to disk")

Saved model to disk

In [ ]:
#Loading our model
json_file = open('model4.json', 'r')
loaded_model4_json = json_file.read()
json_file.close()
loaded_model4 = model_from_json(loaded_model4_json)
# load weights into new model
loaded_model4.load_weights("model4.h5")
print("Loaded model from disk")
loaded_model4.compile(loss='mse', optimizer='adam')

Loaded model from disk

In [ ]:
pred = loaded_model4.predict(x_test_norm)
print(np.sqrt(mean_squared_error(y_test,pred)))
print(mean_absolute_error(y_test, pred))

0.09024721
0.036459025

In [ ]:
#Finding pearson's correlation coefficient between
#real value and predicted value

y_test = np.array(y_test, dtype ='float32')
pred = np.array(pred, dtype ='float32')
new_y = y_test.reshape(565864, 1)
new_y = np.squeeze(new_y)
new_p = pred.reshape(565864, 1)
new_p = np.squeeze(new_p)

from scipy.stats import pearsonr
corr, _ = pearsonr(new_p, new_y)
print('Pearsons correlation: %.4f' % corr)

Pearsons correlation: 0.9601

#NN #5
- 3 dense layers
- 96 to 1000 to 8 to 48
- 20 epochs

In [ ]:
# define the keras model
model5 = Sequential()
model5.add(Dense(1000, input_dim=100, activation='relu'))
model5.add(Dense(8, activation='relu'))
model5.add(Dense(52))
model5.compile(loss='mse', optimizer='adam')
# fit the keras model on the dataset
model5.fit(x_train_norm, y_train, epochs=20)

Epoch 1/20
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0179
Epoch 2/20
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0117
Epoch 3/20
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0113
Epoch 4/20
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0110
Epoch 5/20
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0107
Epoch 6/20
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0105
Epoch 7/20
3061/3061 [==============================] - 11s 3ms/step - loss: 0.0103
Epoch 8/20
3061/3061 [==============================] - 12s 4ms/step - loss: 0.0101
Epoch 9/20
3061/3061 [==============================] - 16s 5ms/step - loss: 0.0099
Epoch 10/20
3061/3061 [==============================] - 15s 5ms/step - loss: 0.0098
Epoch 11/20
3061/3061 [==============================] - 12s 4ms/step - loss: 0.0097
Epoch 12/20
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0096
Epoch 13/20
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0095
Epoch 14/20
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0094
Epoch 15/20
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0094
Epoch 16/20
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0093
Epoch 17/20
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0091
Epoch 18/20
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0091
Epoch 19/20
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0090
Epoch 20/20
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0090

In [ ]:
#Saving our model
from keras.models import model_from_json
model5_json = model5.to_json()
with open("model5.json", "w") as json_file:
    json_file.write(model5_json)
model5.save_weights("model5.h5")
print("Saved model to disk")

Saved model to disk

In [ ]:
#Loading our model
json_file = open('model5.json', 'r')
loaded_model5_json = json_file.read()
json_file.close()
loaded_model5 = model_from_json(loaded_model5_json)
# load weights into new model
loaded_model5.load_weights("model5.h5")
print("Loaded model from disk")
loaded_model5.compile(loss='mse', optimizer='adam')

Loaded model from disk

In [ ]:
pred = loaded_model5.predict(x_test_norm)
print(np.sqrt(mean_squared_error(y_test,pred)))
print(mean_absolute_error(y_test, pred))

0.09127045
0.042464845

In [ ]:
#Finding pearson's correlation coefficient between
#real value and predicted value

y_test = np.array(y_test, dtype ='float32')
pred = np.array(pred, dtype ='float32')
new_y = y_test.reshape(565864, 1)
new_y = np.squeeze(new_y)
new_p = pred.reshape(565864, 1)
new_p = np.squeeze(new_p)

from scipy.stats import pearsonr
corr, _ = pearsonr(new_p, new_y)
print('Pearsons correlation: %.4f' % corr)

Pearsons correlation: 0.9584

#NN #6
- 3 dense layers
- 96 to 100 to 100 to 48
- 30 epochs

In [ ]:
model6 = Sequential()
model6.add(Input(shape=(100,)))
model6.add(Dense(100, activation = 'relu'))
model6.add(Dense(100, activation = 'relu'))
model6.add(Dense(52, activation = 'relu'))
model6.compile(loss='mse', optimizer='adam')
model6.fit(x_train_norm, y_train, epochs=30)

Epoch 1/30
3061/3061 [==============================] - 9s 3ms/step - loss: 0.0399
Epoch 2/30
3061/3061 [==============================] - 7s 2ms/step - loss: 0.0385
Epoch 3/30
3061/3061 [==============================] - 7s 2ms/step - loss: 0.0381
Epoch 4/30
3061/3061 [==============================] - 7s 2ms/step - loss: 0.0378
Epoch 5/30
3061/3061 [==============================] - 7s 2ms/step - loss: 0.0375
Epoch 6/30
3061/3061 [==============================] - 7s 2ms/step - loss: 0.0373
Epoch 7/30
3061/3061 [==============================] - 7s 2ms/step - loss: 0.0371
Epoch 8/30
3061/3061 [==============================] - 7s 2ms/step - loss: 0.0369
Epoch 9/30
3061/3061 [==============================] - 7s 2ms/step - loss: 0.0368
Epoch 10/30
3061/3061 [==============================] - 7s 2ms/step - loss: 0.0366
Epoch 11/30
3061/3061 [==============================] - 7s 2ms/step - loss: 0.0365
Epoch 12/30
3061/3061 [==============================] - 7s 2ms/step - loss: 0.0364
Epoch 13/30
3061/3061 [==============================] - 7s 2ms/step - loss: 0.0363
Epoch 14/30
3061/3061 [==============================] - 7s 2ms/step - loss: 0.0362
Epoch 15/30
3061/3061 [==============================] - 7s 2ms/step - loss: 0.0361
Epoch 16/30
3061/3061 [==============================] - 8s 3ms/step - loss: 0.0347
Epoch 17/30
3061/3061 [==============================] - 7s 2ms/step - loss: 0.0312
Epoch 18/30
3061/3061 [==============================] - 7s 2ms/step - loss: 0.0311
Epoch 19/30
3061/3061 [==============================] - 7s 2ms/step - loss: 0.0310
Epoch 20/30
3061/3061 [==============================] - 7s 2ms/step - loss: 0.0310
Epoch 21/30
3061/3061 [==============================] - 7s 2ms/step - loss: 0.0309
Epoch 22/30
3061/3061 [==============================] - 7s 2ms/step - loss: 0.0308
Epoch 23/30
3061/3061 [==============================] - 7s 2ms/step - loss: 0.0308
Epoch 24/30
3061/3061 [==============================] - 7s 2ms/step - loss: 0.0308
Epoch 25/30
3061/3061 [==============================] - 7s 2ms/step - loss: 0.0307
Epoch 26/30
3061/3061 [==============================] - 7s 2ms/step - loss: 0.0307
Epoch 27/30
3061/3061 [==============================] - 7s 2ms/step - loss: 0.0306
Epoch 28/30
3061/3061 [==============================] - 7s 2ms/step - loss: 0.0306
Epoch 29/30
3061/3061 [==============================] - 7s 2ms/step - loss: 0.0306
Epoch 30/30
3061/3061 [==============================] - 7s 2ms/step - loss: 0.0305

In [ ]:
#Saving our model
from keras.models import model_from_json
model6_json = model6.to_json()
with open("model6.json", "w") as json_file:
    json_file.write(model6_json)
model6.save_weights("model6.h5")
print("Saved model to disk")

Saved model to disk

In [ ]:
#Loading our model
json_file = open('model6.json', 'r')
loaded_model6_json = json_file.read()
json_file.close()
loaded_model6 = model_from_json(loaded_model6_json)
# load weights into new model
loaded_model6.load_weights("model6.h5")
print("Loaded model from disk")
loaded_model6.compile(loss='mse', optimizer='adam')

Loaded model from disk

In [ ]:
pred = loaded_model6.predict(x_test_norm)
print(np.sqrt(mean_squared_error(y_test,pred)))
print(mean_absolute_error(y_test, pred))

0.17570928
0.061374787

In [ ]:
#Finding pearson's correlation coefficient between
#real value and predicted value

y_test = np.array(y_test, dtype ='float32')
pred = np.array(pred, dtype ='float32')
new_y = y_test.reshape(565864, 1)
new_y = np.squeeze(new_y)
new_p = pred.reshape(565864, 1)
new_p = np.squeeze(new_p)

from scipy.stats import pearsonr
corr, _ = pearsonr(new_p, new_y)
print('Pearsons correlation: %.4f' % corr)

Pearsons correlation: 0.8360

#NN #7
- 3 dense layers
- 96 to 1000 to 8 to 48
- 30 epochs

In [ ]:
# define the keras model
model7 = Sequential()
model7.add(Dense(1000, input_dim=100, activation='relu'))
model7.add(Dense(8, activation='relu'))
model7.add(Dense(52))
model7.compile(loss='mse', optimizer='adam')
# fit the keras model on the dataset
model7.fit(x_train_norm, y_train, epochs=30)

Epoch 1/30
3061/3061 [==============================] - 12s 4ms/step - loss: 0.0160
Epoch 2/30
3061/3061 [==============================] - 11s 4ms/step - loss: 0.0097
Epoch 3/30
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0093
Epoch 4/30
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0089
Epoch 5/30
3061/3061 [==============================] - 11s 4ms/step - loss: 0.0086
Epoch 6/30
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0083
Epoch 7/30
3061/3061 [==============================] - 11s 3ms/step - loss: 0.0082
Epoch 8/30
3061/3061 [==============================] - 11s 3ms/step - loss: 0.0080
Epoch 9/30
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0078
Epoch 10/30
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0077
Epoch 11/30
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0076
Epoch 12/30
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0075
Epoch 13/30
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0074
Epoch 14/30
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0073
Epoch 15/30
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0072
Epoch 16/30
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0072
Epoch 17/30
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0071
Epoch 18/30
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0070
Epoch 19/30
3061/3061 [==============================] - 9s 3ms/step - loss: 0.0070
Epoch 20/30
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0069
Epoch 21/30
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0068
Epoch 22/30
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0068
Epoch 23/30
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0067
Epoch 24/30
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0067
Epoch 25/30
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0067
Epoch 26/30
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0067
Epoch 27/30
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0066
Epoch 28/30
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0066
Epoch 29/30
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0066
Epoch 30/30
3061/3061 [==============================] - 10s 3ms/step - loss: 0.0065

In [ ]:
#Saving our model
from keras.models import model_from_json
model7_json = model7.to_json()
with open("model7.json", "w") as json_file:
    json_file.write(model7_json)
model7.save_weights("model7.h5")
print("Saved model to disk")

Saved model to disk

In [ ]:
#Loading our model
json_file = open('model7.json', 'r')
loaded_model7_json = json_file.read()
json_file.close()
loaded_model7 = model_from_json(loaded_model7_json)
# load weights into new model
loaded_model7.load_weights("model7.h5")
print("Loaded model from disk")
loaded_model7.compile(loss='mse', optimizer='adam')

Loaded model from disk

In [ ]:
pred = loaded_model7.predict(x_test_norm)
print(np.sqrt(mean_squared_error(y_test,pred)))
print(mean_absolute_error(y_test, pred))

0.08216511
0.035951976

In [ ]:
#Finding pearson's correlation coefficient between
#real value and predicted value

y_test = np.array(y_test, dtype ='float32')
pred = np.array(pred, dtype ='float32')
new_y = y_test.reshape(565864, 1)
new_y = np.squeeze(new_y)
new_p = pred.reshape(565864, 1)
new_p = np.squeeze(new_p)

from scipy.stats import pearsonr
corr, _ = pearsonr(new_p, new_y)
print('Pearsons correlation: %.4f' % corr)

Pearsons correlation: 0.9662